baseURL = "https://efragments.com"
languageCode = "en-gb"
title = "efragments"
publishdir = "dist"
assetdir = "."

[params]
author = "Will Hughes"
authorimage = "/img/headshot.png"
dateformat = "1 January 2000"

[params.font]
name = "Merriweather"
weights = "300,400"

[permalinks]
notes = "/:title/"

[params.unpkg]
css = [
	"normalize.css/normalize.css",
]
